name: Main

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: debian-10
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 1.17
      - name: Maven Package
        run: mvn -B clean package -DskipTests
