name: Main

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Maven Package
        run: mvn -B clean package -DskipTests
  deploy:
     runs-on: ubuntu-latest
     steps:
          - name: pull war and deploy
            uses: nekiro/ssh-job@main
            with:
              host: ${{ secrets.HOST }}
              user: ${{ secrets.USER }}
              password: ${{ secrets.PASSWORD }}
              command: |
                cd /home/repo
                rm -rf /home/repo/*
                git init
                git clone https://github.com/kopyshov/CurrencyExchange.git
                sudo chmod +x ./mvnw
                ./mvnw tomkat:deploy
                cp /target/*.war /home/tomcat/webapps
              
