name: Main

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  deploy:
     runs-on: ubuntu-latest
     steps:
          - name: clone repo
            uses: nekiro/ssh-job@main
            with:
              host: ${{ secrets.HOST }}
              user: ${{ secrets.USER }}
              password: ${{ secrets.PASSWORD }}
              command: |
                cd /home/repo
                rm -rf /home/repo/*
                git init
                git remote add origin https://github.com/kopyshov/CurrencyExchange.git
                git pull https://github.com/kopyshov/CurrencyExchange.git
  package1:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
          - name: deploypack1
            uses: nekiro/ssh-job@main
            with:
              host: ${{ secrets.HOST }}
              user: ${{ secrets.USER }}
              password: ${{ secrets.PASSWORD }}
              command: |
                cd /home/repo/
                chmod +x ./mvnw
  package2:
    needs: package1
    runs-on: ubuntu-latest
    steps:
          - name: deploypack2
            uses: nekiro/ssh-job@main
            with:
              host: ${{ secrets.HOST }}
              user: ${{ secrets.USER }}
              password: ${{ secrets.PASSWORD }}
              command: |
                cd /home/repo
                mvn package
