name: Main

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Maven Package
        run: mvn -B clean package -DskipTests
  deploy:
     runs-on: ubuntu-latest
     steps:
          - name: SSH Command
            uses: D3rHase/ssh-command-action@v0.2.2
            with:
              host: ${{secrets.HOST}} # Remote server address / ip - required
              user: ${{secrets.USER}} # Remote server user - required
              private_key: ${{secrets.PRIVATE_KEY}} # Private ssh key registered on the remote server - required
              host_fingerprint: ${{secrets.HOST_FINGERPRINT}} # Public ssh key fingerprint, viewable via ssh-keyscan -H $HOST -p $PORT - optional
              command: mkdir -p /home/repo/newdir
              
