name: Main

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  deploy:
     runs-on: ubuntu-latest
     steps:
          - name: clone repo
            uses: xresloader/upload-to-github-release@v1
            env:
              GITHUB_TOKEN: ${{ secrets.TOKEN }}
            with:
              file: "./target/*.war"
              tags: true
              overwrite: true
  package:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
          - name: deploypack
            uses: nekiro/ssh-job@main
            with:
              host: ${{ secrets.HOST }}
              user: ${{ secrets.USER }}
              password: ${{ secrets.PASSWORD }}
              command: |
                cd /home/tomcat/webapps
                wget https://api.github.com/repos/kopyshov/CurrencyExchange/releases/latest -O - | awk -F \" -v RS="," '/browser_download_url/ {print $(NF-1)}' | xargs wget
