name: Main

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          file: "./target/*.war"
          overwrite: true
  deploy:
     needs: build
     runs-on: ubuntu-latest
     steps:
          - name: clone repo
            uses: nekiro/ssh-job@main
            with:
              host: ${{ secrets.HOST }}
              user: ${{ secrets.USER }}
              password: ${{ secrets.PASSWORD }}
              command: |
	      	cd /home
